defaults: &defaults
  working_directory: ~/build

version: 2
jobs:
 build:
   <<: *defaults
   docker:
      - image: docker:stable
   steps:
     - checkout

     - setup_remote_docker:
         docker_layer_caching: true

     - run: |
         cd rest/
         mkdir tar
         docker build -t $CIRCLE_PROJECT_REPONAME:dev .

 save:
   <<: *defaults
   docker:
      - image: docker:stable
   steps:
     - setup_remote_docker:
         docker_layer_caching: true

     - attach_workspace:
         at: ~/build/rest/

     - run: |
         docker save -o tar/$CIRCLE_PROJECT_REPONAME.tar $CIRCLE_PROJECT_REPONAME
     - persist_to_workspace:
         root: ~/build/rest/
         paths:
           - tar

 deploy:
   <<: *defaults
   docker:
      - image: docker:stable
   steps:
     - setup_remote_docker:
         docker_layer_caching: true

     - attach_workspace:
         at: ~/build/rest/

     - run: |
         cd rest/tar
         docker load -i $CIRCLE_PROJECT_REPONAME.tar
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         docker tag $CIRCLE_PROJECT_REPONAME:dev $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev
         docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - save:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - save
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
