version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     
     - run: |
         cd rest/
	 WORKSPACE="/workspace/tar"
         docker build -t $CIRCLE_PROJECT_REPONAME:dev .
         echo "Successfully built docker image"
         docker save -o $WORKSPACE/$CIRCLE_PROJECT_REPONAME.tar $CIRCLE_PROJECT_REPONAME
         echo "Successfully saved the docker image"
     - persist_to_workspace:
         root: /workspace
         paths:
           - tar

 deploy:
   machine: true
   steps:
     - attach_workspace:
         at: /workspace
     - checkout

     - run: |
         docker load -i $WORKSPACE/$CIRCLE_PROJECT_REPONAME.tar
	 echo "Succesfully loaded the docker image"
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         echo "Successfully logged-in to docker"
         docker tag $CIRCLE_PROJECT_REPONAME:dev $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev
         echo "Successfully tagged the image for upload" 
         docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev
         echo "Successfully pushed the image"

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
