# 
defaults: &defaults
  working_directory: ~/build

version: 2
jobs:

 build:
   <<: *defaults
   steps:
     - checkout
     
     - run: |
         cd rest/
         mkdir tar
         docker build -t $CIRCLE_PROJECT_REPONAME:dev .
         echo "Successfully built docker image"


         docker save -o tar/$CIRCLE_PROJECT_REPONAME.tar $CIRCLE_PROJECT_REPONAME
         echo "Successfully saved the docker image"
         pwd
         ls -ltr tar/
     - persist_to_workspace:
         root: ~/build/rest/
         paths:
           - tar

 deploy:
   <<: *defaults
   steps:
     - run: pwd
     - attach_workspace:
         at: ~/build/rest/

     - run: |
         ls
         pwd
         cd rest/tar
         ls
         docker load -i $CIRCLE_PROJECT_REPONAME.tar
         echo "Succesfully loaded the docker image"
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         echo "Successfully logged-in to docker"
         docker tag $CIRCLE_PROJECT_REPONAME:dev $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev
         echo "Successfully tagged the image for upload" 
         docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev
         echo "Successfully pushed the image"

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
