version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     
     - run: |
         cd rest/
         docker build -t $CIRCLE_PROJECT_REPONAME:dev .
         echo "Successfully built docker image"
         docker save -o $CIRCLE_PROJECT_REPONAME.tar CIRCLE_PROJECT_REPONAME
         echo "Successfully saved the docker image"
         docker login -u $CIRCLE_USERNAME -p Saanvi_14
         echo "Successfully logged-in to docker"
         docker tag $CIRCLE_PROJECT_REPONAME:dev $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev
         echo "Successfully tagged the image for upload" 
         docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev
         echo "Successfully pushed the image"
