defaults: &defaults
  working_directory: /workspace
  testing_directory: /testspace

  docker:
     - image: docker:stable

version: 2
jobs:
 build:
   <<: *defaults
   steps:
     - checkout

     - setup_remote_docker:
         docker_layer_caching: true

     - run:
         name: Build image
         command: cd rest && docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev .
     - run:
         name: Save image
         command: mkdir tar && docker save -o tar/$CIRCLE_PROJECT_REPONAME.tar $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
     - run:
         name: npm testcase execution
         command: cd rest && npm test

     - persist_to_workspace:
         root: /testspace
         paths:
           - rest

     - persist_to_workspace:
         root: /workspace
         paths:
           - tar

 test:
   <<: *defaults
   steps:
     - setup_remote_docker:
         docker_layer_caching: true

     - attach_workspace:
         at: /testspace

     - run:
         name: execute npm testcases
         command: npm test

 deploy:
   <<: *defaults
   steps:
     - setup_remote_docker:
         docker_layer_caching: true

     - attach_workspace:
         at: /workspace

     - run:
         name: Load image
         command: cd tar && docker load -i $CIRCLE_PROJECT_REPONAME.tar
     - run:
         name: Login to docker hub
         command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
     - run:
         name: Deploy saas_ux image to docker hub
         command: docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /.*/

      - test:
          requires:
            - build
          filters:
            tags:
              only:
                - /.*/

      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
