version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.0.0
jobs:
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - checkout
      - run:
          name: build container
          command: cd rest && docker build -t ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:dev .
      - anchore/analyze_local_image:
          image_name: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:dev
          timeout: '500'

workflows:
  version: 2.1
  commit-workflow:
    jobs:
      - local_image_scan:
          filters:
            tags:
              only:
                - /.*/
