version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     
     - run: |
         cd rest/
         docker build -t ssubbanna/saas_ux:dev .
         docker save -o saas_ux.tar saas_ux
         docker login -u $CIRCLE_USERNAME -p Saanvi_14
         docker tag saas_ux:dev ssubbanna/saas_ux:dev
         docker push saas_ux:dev

     # deploy the image
#     - run: docker push ssubbanna/saas_ux:$CIRCLE_BRANCH
