version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     
     - run: |
         cd rest/
         docker build -t saas_ux:dev .
         echo "Successfully built docker image"
         docker save -o saas_ux.tar saas_ux
         echo "Successfully saved the docker image"
         docker login -u $CIRCLE_USERNAME -p Saanvi_14
         echo "Successfully logged-in to docker"
         docker tag saas_ux:dev ssubbanna/saas_ux:dev
         echo "Successfully tagged the image for upload" 
         docker push saas_ux:dev
         echo "Successfully pushed the image"

     # deploy the image
#     - run: docker push ssubbanna/saas_ux:$CIRCLE_BRANCH
