defaults: &defaults
  working_directory: ~/build

version: 2
jobs:
 build:
   <<: *defaults
   docker:
      - image: docker:stable
   steps:
     - checkout

     - setup_remote_docker:
         docker_layer_caching: true

     - run:
         name: change directory
         command: cd rest
     - run:
         name: make directory
         command: mkdir tar
     - run:
         name: Build image
         command: docker build -t $CIRCLE_PROJECT_REPONAME:dev .
     - run:
         name: Save image
         command: docker save -o tar/$CIRCLE_PROJECT_REPONAME.tar $CIRCLE_PROJECT_REPONAME
     - persist_to_workspace:
         root: ~/build/rest/
         paths:
           - tar

 deploy:
   <<: *defaults
   docker:
      - image: docker:stable
   steps:
     - setup_remote_docker:
         docker_layer_caching: true

     - attach_workspace:
         at: ~/build/rest/

     - run: 
         name: change to working directory
         command: cd rest/tar
     - run:
         name: Load image
         command: docker load -i $CIRCLE_PROJECT_REPONAME.tar
     - run:
         name: Login to Docker 
         command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
     - run:
         name: Tag the docker image
         command: docker tag $CIRCLE_PROJECT_REPONAME:dev $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev
     - run:
         name: Deploy the image to docker hub
         command: docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
