_job_defaults: &job_defaults
  working_directory: ~/test_ux/rest/

version: 2
jobs:
  build:
    docker: 
      - image: docker:17.06.0-ce-git
    steps:
      - checkout 
      - run: 
          name: Inspec Lint Check
          command: |
            pwd
            ls
