version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u ssubbanna -p Saanvi_14

     # build the application image
     - run: |
         cd rest/
         docker build -t ssubbanna/saas_ux:$CIRCLE_BRANCH .

     # deploy the image
#     - run: docker push ssubbanna/saas_ux:$CIRCLE_BRANCH
