version: "3"
services:
    rest:
        image: abhsob/extreme_central_rest:1.1
        ports:
            - "6080:6080"
        depends_on:
            - redis
    redis:
        image: redis:4.0.11
